---
- name: ansible-pull-playbook
  hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: update system
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/install_packages.yml
    - include: tasks/remove_packages.yml

