---
- name: ansible-pull-playbook
  hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: uddate repo
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml

